version: '3'

services:
  mongodb:
    image: mongo:5.0.15
    restart: on-failure
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - ./mongo_data:/data/db

  rest_api:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongodb
