version: '3'

services:
  mongodb:
    image: mongo:5.0.15
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'yolo'
      MONGO_INITDB_ROOT_PASSWORD: 'very_strong_password'
    volumes:
      - ./mongo_data:/data/db

  rest_api:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      MONGO_DATABASE: 'admin'
      MONGO_CONNECTION_STRING: 'mongodb://yolo:very_strong_password@mongodb:27017/admin'
    depends_on:
      - mongodb
